pull_request_rules:
  - name: Automatic merge on dependabot
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=CI
      - check-success=Platforms
    actions:
      merge:
        method: squash
