[workspace]
members = [
    "sentinel-core",
    "sentinel-macros",
]

exclude = [
    "examples/ebpf/probes",
    "examples/ebpf/userspace",
    "middleware/tower",
    "middleware/tower/example",
    "middleware/tonic",
    "middleware/tonic/example",
]
