[package]
edition = "2021"
license = "MIT"
name = "sentinel-tower"
publish = false
version = "0.1.0"

[features]
default = []
http = ["dep:http"]

[dependencies]
sentinel-core = {version="0.1.2", features=["async"]}
tower = "0.4"
http = {version = "0.2", optional = true}
