[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2018"

[dev-dependencies]
sentinel-rs = { version = "0.1.0", path = "../sentinel", features = ["full"] }
rand = "0.8.4"

[[example]]
name = "hello_world"
path = "hello_world.rs"
