version: '2'
services:
  proxy:
    build:
      context: ./docker
      dockerfile: Dockerfile.proxy
    volumes:
      - ./docker/envoy.yaml:/etc/envoy.yaml
      - ./docker/sentinel_envoy_module.wasm:/etc/sentinel_envoy_module.wasm
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "18000:80"
      - "18001:8001"

  web_service:
    image: hashicorp/http-echo
    command:
      - '-text="Hi from web service!"'
    networks:
      envoymesh:
        aliases:
          - web_service
    expose:
      - "5678"

networks:
  envoymesh: {}
