version: '2'
services:
  proxy:
    build:
      context: ./docker
      dockerfile: Dockerfile.proxy
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy.yaml
      - ./target/wasm32-unknown-unknown/release/myenvoyfilter.wasm:/etc/myenvoyfilter.wasm
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "18000:80"
      - "18001:8001"
      - "18002:8002"

  web_service:
    image: hashicorp/http-echo
    command:
      - '-text="Hi from web service!"'
    networks:
      envoymesh:
        aliases:
          - web_service
    expose:
      - "5678"
    ports:
      - "18080:5678"

networks:
  envoymesh: {}
