name: Clippy

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  schedule: 
    - cron: '0 0 * * 0' # Sunday

jobs:    
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - name: Install clippy
        run: rustup component add clippy
      - name: "clippy --all"
        run: cargo clippy --all --tests --all-features
