# use grcov to analyze code coverage

name: grcov

on:
  push:
    branches: 
      - main
  schedule: 
    - cron: '0 0 * * 0' # Sunday

jobs:
  coverage:
      name: Coverage
      runs-on: ubuntu-latest
      env:
        RUSTFLAGS: -Zinstrument-coverage
        LLVM_PROFILE_FILE: "sentinel-rs-%p-%m.profraw"
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} 
      steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: nightly
            default: true
        - name: install grcov
          run: cargo install grcov
        - name: install llvm tools
          run: rustup component add llvm-tools-preview
        - name: build project
          run: cargo build
        - name: test project
          run: cargo test
        - name: test project
          run: cargo test -- --ignored --test-threads=1
        - name: generate lcov.info file 
          run: grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
        #- name: commit codecov
          #run: bash <(curl -s https://codecov.io/bash) -f lcov.info